  name: "Relay ${id}"
  restore_mode: RESTORE_DEFAULT_OFF
  
  pin:
    sn74hc595: sn74hc595_relays
    # Use pin number ${id}
    number: ${id}
    inverted: false
  id: relay_${id}
 
  on_turn_on:
  - logger.log: "Switch Turned On!"
  - lambda: |-
      if (id(selected_relay0) == ${id}) id(Led_0).turn_on();
      if (id(selected_relay1) == ${id}) id(Led_1).turn_on();
      if (id(selected_relay2) == ${id}) id(Led_2).turn_on();
      if (id(selected_relay3) == ${id}) id(Led_3).turn_on();
      if (id(selected_relay4) == ${id}) id(Led_4).turn_on();
      if (id(selected_relay5) == ${id}) id(Led_5).turn_on();
      if (id(selected_relay6) == ${id}) id(Led_6).turn_on();
      if (id(selected_relay7) == ${id}) id(Led_7).turn_on();
  - rtttl.play: 'Click:d=8,o=5,b=400:c'
  on_turn_off:
  - logger.log: "Switch Turned Off!"
  - lambda: |-
      if (id(selected_relay0) == ${id}) id(Led_0).turn_off();
      if (id(selected_relay1) == ${id}) id(Led_1).turn_off();
      if (id(selected_relay2) == ${id}) id(Led_2).turn_off();
      if (id(selected_relay3) == ${id}) id(Led_3).turn_off();
      if (id(selected_relay4) == ${id}) id(Led_4).turn_off();
      if (id(selected_relay5) == ${id}) id(Led_5).turn_off();
      if (id(selected_relay6) == ${id}) id(Led_6).turn_off();
      if (id(selected_relay7) == ${id}) id(Led_7).turn_off();
  - rtttl.play: 'Click:d=8,o=5,b=400:c'
